# Exercici 1

#### Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [18]:
import statistics
from statistics import mode
import numpy as np

nums = np.array ([15,67,41,19,6,8])
print("Dimensions: " + str(nums.ndim))

if nums.ndim!=1:
    print("Error")
else:
    print("Mitja: " + str(statistics.mean(nums)))

    print("Mitjada: " + str(statistics.median(nums)))
    print("Moda: " + str(mode(nums)))

    nmin=min(nums)
    nmax=max(nums)
    print("Rango: " + str(nmax-nmin))

    print("Desviació estandar: " + str(statistics.pstdev(nums)))

Dimensions: 1
Mitja: 26
Mitjada: 17.0
Moda: 15
Rango: 61
Desviació estandar: 21.587033144922902


# Exercici 2

#### Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100

In [20]:
import numpy as np

#nums = np.random.rand(5,5)
#print(nums)
nums = np.random.uniform(low=0, high=100, size=(5,5))
print(nums)


[[0.85441064 0.5412147  0.26656401 0.69516994 0.82349532]
 [0.01778879 0.99121722 0.09689842 0.27043645 0.30812605]
 [0.38006426 0.62181126 0.9304326  0.13443602 0.89129676]
 [0.9305235  0.83367603 0.99564286 0.23588427 0.25504264]
 [0.40915572 0.09222642 0.11893834 0.70878217 0.37507507]]
[[57.60381219 94.44604542 17.35201754 15.30565336 49.22552911]
 [67.44428095 53.51166523 18.01709062 64.39848904 83.33328524]
 [ 3.27721864 20.51369647 17.34588245 29.78964922 55.33050828]
 [41.91440709 62.10937952 16.75492741 21.24734554 21.2398006 ]
 [63.57457911 38.84545507 91.67286795 28.36187058 84.958789  ]]


# Exercici 3

#### Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [26]:
import numpy as np

nums = np.random.uniform(low=0, high=100, size=(3,3))
print("Dimensions: " + str(nums.ndim))
s = np.sum(nums, axis=0) # Columna
print(s)
s = np.sum(nums, axis=1) # Fila
print(s)



Dimensions: 2
[174.25467642 176.89943814 101.64360235]
[125.1776122  170.01893999 157.60116472]


# Exercici 4

#### Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [54]:
#np.corrcoef(x, y)
import numpy as np

nums = np.array([[2, 1],[3, 3],[4, 2],[4, 4],[5, 4],[6, 4],[6, 6],[7, 4],[7, 6],[8, 7],[10, 9],[10, 10]])
print(nums)
print("Dimensions: " + str(nums.ndim))
muestras=len(nums)
print("Muestras: " + str(muestras))
res = np.sum(nums, axis=0) # Columna
print(res)
x=res[0]
y=res[1]
print("x=" + str(x))
print("y=" + str(y))
xy_arr=np.prod(nums, axis=1)
xy=np.sum(xy_arr)
print("xy=" + str(xy))
x2y2_arr=np.square(nums)
x2y2=np.sum(x2y2_arr, axis=0)
x2=x2y2[0]
y2=x2y2[1]
print("x2=" + str(x2))
print("y2=" + str(y2))
x_mediaAritmetica=x/muestras
print("Media aritmetica x=" + str(x_mediaAritmetica))
y_mediaAritmetica=y/muestras
print("Media aritmetica y=" + str(y_mediaAritmetica))
xy_cavarianza=(xy/muestras)-(x_mediaAritmetica*y_mediaAritmetica)
print("Cavarianza=" + str(xy_cavarianza))
x_desviacionTipica=np.sqrt((x2/muestras)-(x_mediaAritmetica**2))
print("Desviación tipica x=" + str(x_desviacionTipica))
y_desviacionTipica=np.sqrt((y2/muestras)-(y_mediaAritmetica**2))
print("Desviación tipica y=" + str(y_desviacionTipica))
coeficienteCorrelacionLineal=xy_cavarianza/(x_desviacionTipica*y_desviacionTipica)
print("Coeficiente de correlacion lineal=" + str(coeficienteCorrelacionLineal))



[[ 2  1]
 [ 3  3]
 [ 4  2]
 [ 4  4]
 [ 5  4]
 [ 6  4]
 [ 6  6]
 [ 7  4]
 [ 7  6]
 [ 8  7]
 [10  9]
 [10 10]]
Dimensions: 2
Muestras: 12
[72 60]
x=72
y=60
xy=431
x2=504
y2=380
Media aritmetica x=6.0
Media aritmetica y=5.0
Cavarianza=5.916666666666664
Desviación tipica x=2.449489742783178
Desviación tipica y=2.5819888974716116
Coeficiente de correlacion lineal=0.9355071411331451
